name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Node.js ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies 🔧
        run: npm ci

      - name: Create environment files 🛠️
        run: |
          mkdir -p src/environment
          cp src/environment/environment.template.ts src/environment/environment.ts
          cp src/environment/environment.template.ts src/environment/environment.prod.ts
          # Set production to true in prod file
          sed -i 's/production: false/production: true/g' src/environment/environment.prod.ts

      - name: Build 🏗️
        run: npm run build:prod

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/send-mail/browser # Angular 17 application builder outputs to /browser
          branch: gh-pages
